#
# Copyright (c) 2023 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   Mahmoud Mazouz, <hello@fuzzypixelz.com>
#

name: Sync Cargo lockfile and Rust toolchain
description: Whenever the lockfile and/or the toolchain file of the host repository go out of sync with Zenoh's, this action will open a pull request to update them.
inputs:
  source:
    description: "Source repository of Zenoh as '{owner}/{repo}'"
    required: true
    default: eclipse-zenoh/zenoh
  branch:
    description: "Branch of Zenoh to checkout"
    required: true
    default: master
  manifest-path:
    description: "Path to the manifest whose lockfile is to be synced"
    required: true
    default: "Cargo.toml"
  toolchain-path:
    description: "Path to the Rust toolchain to sync"
    required: true
    default: "rust-toolchain.toml"
runs:
  using: "composite"
  steps:
    - name: Checkout this repository
      uses: actions/checkout@v4
    - name: Override rust-toolchain.toml with Zenoh's
      # This should be done before we install the toolchain
      run: curl "https://raw.githubusercontent.com/${{ inputs.source }}/${{ inputs.branch }}/rust-toolchain.toml" --output ${{ inputs.toolchain-path }}
      shell: bash
    - name: Install Rust toolchain
      # Showing the active Rust toolchain (defined by the rust-toolchain.toml file)
      # will have the side effect of installing it; if it's not installed already.
      run: rustup show
      shell: bash
    - name: Override Cargo.lock with Zenoh's
      run: |
        MANIFEST_PATH=${{ inputs.manifest-path }}
        curl "https://raw.githubusercontent.com/${{ inputs.source }}/${{ inputs.branch }}/Cargo.lock" --output ${MANIFEST_PATH/toml/lock}
      shell: bash
    - name: Fixup Cargo.lock
      # Checking the package for errors will rectify the Cargo.lock while preserving
      # the dependency versions fetched from source.
      run: cargo check --manifest-path ${{ inputs.manifest-path }}
      shell: bash
    - name: Create/Update a pull request if Cargo.lock or rust-toolchain.toml changed
      # If there is a pending PR, this action will simply update it with a forced push
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "automated: Sync `Cargo.lock` and/or `rust-toolchain.toml` with Zenoh's"
        branch: automated/sync-lockfile-and-toolchain
        delete-branch: true
        title: Sync `Cargo.lock` and/or `rust-toolchain.toml` with Zenoh's
        body: Automated synchronization of Cargo.lock and/or rust-toolchain.toml with Zenoh. This is necessary to ensure plugin ABI compatibility.
